### ISSUE TITLE
Runtime error when trying to use the extension

### ISSUE THREAD

**Issue by Wazbat** [seatonjiang/gitmoji-vscode#54]
This extension works fine on my desktop, however whenever I try to run it on my laptop, with a seperate vscode install, I get the following error:
```log
[2023-06-29 13:46:31.420] [exthost] [info] ExtensionService#_doActivateExtension seatonjiang.gitmoji-vscode, startup: false, activationEvent: 'onCommand:extension.showGitmoji'
[2023-06-29 13:46:31.431] [exthost] [error] Activating extension seatonjiang.gitmoji-vscode failed due to an error:
[2023-06-29 13:46:31.431] [exthost] [error] TypeError: Cannot read properties of undefined (reading 't')
    at Object.<anonymous> (c:\Users\Wazbat\.vscode\extensions\seatonjiang.gitmoji-vscode-1.2.0\out\gitmoji.js:9:34)
    at Module.u._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:1313)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.s._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:14538)
    at Function.p._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:62866)
    at Function.E._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:62234)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at p (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:699)
    at Object.<anonymous> (c:\Users\Wazbat\.vscode\extensions\seatonjiang.gitmoji-vscode-1.2.0\out\extension.js:5:19)
    at Module.u._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:1313)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.s._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:14538)
    at Function.p._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:62866)
    at Function.E._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:62234)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Function.r [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:5:101)
    at b._loadCommonJSModule (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:64346)
    at b._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:14941)
    at b._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:13880)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at E._activate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:8224)
    at E._waitForDepsThenActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:8166)
    at E._initialize (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:7530)
```

Hopefully the stacktrace helps. The extension used to work fine, but then stopped. It has been this way for a few months now, through several updates

**Comment by seatonjiang** [comment]
Hi @Wazbat
Please try to uninstall and reinstall the extension completely, the latest version is currently v1.2.3, if you still have problems, you need to provide the VSCode version

**Comment by Wazbat** [comment]
Hi there,

I have attempted that, and I get the same error in the extension output.
...however upon further investigation, it reinstalled the same version? Vscode seems to display v1.2.3, but once installed it suddenly becomes 1.2.0, and then refuses to show version 1.2.3 as an option??
![image](https://github.com/seatonjiang/gitmoji-vscode/assets/6253896/f70016bd-b00f-44ae-9185-130c2598235a)

https://github.com/seatonjiang/gitmoji-vscode/assets/6253896/380154ce-cf07-48e8-931c-e90687f78764

I am using vscode version 1.71.2

```
Version: 1.71.2 (system setup)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
```

**Comment by seatonjiang** [comment]
Version 1.2.3 requires a VSCode version of at least 1.74.0. Try updating your VSCode version and installing the latest version of Gitmoji.
